version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: "."
    volumes:
      - "./:/app"
    ports:
      - 5000:5000
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      backend:
        aliases:
          - mysql
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fastapi
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=rootpassword
    networks:
      backend:
        aliases:
          - mysql
volumes:
  mysql:
networks:
  backend:
    name: backend-network
